In [30]:
import pickle
import pandas as pds
import datetime

%load_ext autoreload

%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [31]:
file = pickle.load(open('py3dcore_h4c/custom_data/solo_2022_sep_mag_ll_swa_science.p', 'rb'))
data = pds.DataFrame(file)
#data['time'] = pds.to_datetime(data['time'])
#data.set_index('time',  inplace=True)
#data.index.name = None
#data.index = data.index.tz_localize(None)

In [32]:
import numpy as np

file['x'] = file['r'] * np.sin(file['lat']) * np.cos(file['lon'])

In [33]:
file['x']

array([ 0.13914297,  0.13910127,  0.13905956, ..., -0.05783126,
       -0.05811244, -0.05839362])

In [34]:
import py3dcore_h4c

fitter = py3dcore_h4c.ABC_SMC()

model_kwargs = {
        "ensemble_size": int(2**17), #2**17
        "iparams": {
           "cme_longitude": {
               "maximum": -110,
               "minimum": -130
           },
           "cme_latitude": {
               "maximum": -10,
               "minimum": -50
           },
           "cme_inclination": {
               "maximum": 10,
               "minimum": 0
           }, 
            "cme_launch_velocity": {
                "maximum": 750,
                "minimum": 250
            },
            "cme_launch_radius": {
                "maximum": 30,
                "minimum": 5
            }
        }
    }

t_launch = datetime.datetime(2022, 6, 2, 6, tzinfo=datetime.timezone.utc)

t_s_psp = datetime.datetime(2022, 6, 2, 12, tzinfo=datetime.timezone.utc)
t_e_psp = datetime.datetime(2022, 6, 3, 6, tzinfo=datetime.timezone.utc)

t_psp = [datetime.datetime(2022, 6, 2, 13, tzinfo=datetime.timezone.utc),
    datetime.datetime(2022, 6, 2, 14, tzinfo=datetime.timezone.utc),
    datetime.datetime(2022, 6, 2, 15, tzinfo=datetime.timezone.utc),
    datetime.datetime(2022, 6, 2, 16, tzinfo=datetime.timezone.utc)]


fitter.initialize(t_launch, py3dcore_h4c.ToroidalModel, model_kwargs)
fitter.add_observer("PSP", t_psp, t_s_psp, t_e_psp)



In [35]:
fitter.observers

[['PSP',
  [datetime.datetime(2022, 6, 2, 13, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2022, 6, 2, 14, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2022, 6, 2, 15, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2022, 6, 2, 16, 0, tzinfo=datetime.timezone.utc)],
  datetime.datetime(2022, 6, 2, 12, 0, tzinfo=datetime.timezone.utc),
  datetime.datetime(2022, 6, 3, 6, 0, tzinfo=datetime.timezone.utc),
  None]]

In [36]:
import heliosat

observer_obj = getattr(heliosat, 'PSP')()

In [37]:
dt_all = [t_s_psp] + t_psp + [t_e_psp]

_, data = observer_obj.get([t_s_psp, t_e_psp], "mag", reference_frame= 'HEEQ', sampling_freq=300, use_cache=True, as_endpoints=True)
tra = observer_obj.trajectory(dt_all, reference_frame='HEEQ', data_key = "pos")

In [38]:
tra

array([[ 0.03270647, -0.06253744, -0.00435444],
       [ 0.03625155, -0.06203463, -0.00433431],
       [ 0.03974751, -0.06145127, -0.00430821],
       [ 0.04319256, -0.0607926 , -0.00427648],
       [ 0.04658539, -0.06006374, -0.00423949],
       [ 0.08857316, -0.04483293, -0.00332971]])

In [17]:
from py3dcore_h4c.fitter.base import FittingData

data_obj = FittingData(fitter.observers, 'HEEQ') 
data_obj.generate_noise("psd", 300)

[[-1.05285896e+02 -5.62792175e+02 -2.43961960e+02]
 [ 7.42871170e+01 -6.29402954e+02 -7.24466019e+01]
 [-6.05077019e+01 -6.28743042e+02 -1.68775635e+02]
 [-7.53965855e+00 -6.56512024e+02 -3.57362442e+01]
 [-3.54195023e+01 -6.26810242e+02  1.90341187e+02]
 [-6.03448601e+01 -6.51321289e+02 -6.79928055e+01]
 [-3.37802315e+01 -7.07948975e+02 -9.59103546e+01]
 [-9.28271027e+01 -7.36282532e+02 -9.82228165e+01]
 [-7.60810242e+01 -7.27990356e+02 -2.86131039e+01]
 [-9.31273270e+01 -4.55535217e+02 -2.68363068e+02]
 [-1.21022545e+02 -5.58738342e+02  1.40962267e+01]
 [-1.12149986e+02 -5.89495667e+02 -5.60987663e+01]
 [-8.21963806e+01 -5.91795898e+02  2.48691463e+01]
 [ 6.68744736e+01 -6.42287598e+02  1.37235550e+02]
 [ 3.46275787e+01 -6.24822937e+02  1.33888809e+02]
 [ 8.53221512e+01 -6.16764648e+02  1.87400177e+02]
 [ 1.20594688e+02 -5.99951904e+02  1.82320099e+02]
 [ 1.68908127e+02 -5.67987976e+02  1.68295822e+02]
 [ 2.26623611e+02 -5.95109497e+02  1.27217896e+02]
 [ 2.61118286e+02 -5.60616089e+

In [26]:
from py3dcore_h4c.fitter.base import CustomData

data_obj = CustomData(fitter.observers, 'HEEQ','solo_2022_sep_mag_ll_swa_science.p') 

In [35]:
import numpy as np

_ = np.linspace(t_s_psp.timestamp(), t_e_psp.timestamp(), int((t_e_psp.timestamp() - t_s_psp.timestamp()) // 300))  
dtp = [datetime.datetime.fromtimestamp(_, datetime.timezone.utc) for _ in _]
tt = [x.replace(tzinfo=None) for x in dtp]

In [25]:
,second=0, microsecond=0 [0]

[datetime.datetime(2022, 9, 1, 0, 0),
 datetime.datetime(2022, 9, 1, 0, 5),
 datetime.datetime(2022, 9, 1, 0, 10),
 datetime.datetime(2022, 9, 1, 0, 15),
 datetime.datetime(2022, 9, 1, 0, 20),
 datetime.datetime(2022, 9, 1, 0, 25),
 datetime.datetime(2022, 9, 1, 0, 30),
 datetime.datetime(2022, 9, 1, 0, 35),
 datetime.datetime(2022, 9, 1, 0, 40),
 datetime.datetime(2022, 9, 1, 0, 45),
 datetime.datetime(2022, 9, 1, 0, 50),
 datetime.datetime(2022, 9, 1, 0, 55),
 datetime.datetime(2022, 9, 1, 1, 0),
 datetime.datetime(2022, 9, 1, 1, 5),
 datetime.datetime(2022, 9, 1, 1, 10),
 datetime.datetime(2022, 9, 1, 1, 15),
 datetime.datetime(2022, 9, 1, 1, 20),
 datetime.datetime(2022, 9, 1, 1, 25),
 datetime.datetime(2022, 9, 1, 1, 30),
 datetime.datetime(2022, 9, 1, 1, 35),
 datetime.datetime(2022, 9, 1, 1, 40),
 datetime.datetime(2022, 9, 1, 1, 45),
 datetime.datetime(2022, 9, 1, 1, 50),
 datetime.datetime(2022, 9, 1, 1, 55),
 datetime.datetime(2022, 9, 1, 2, 0),
 datetime.datetime(2022, 9, 1,

In [42]:
ii = [np.where(file['time']==x)[0][0] for x in tt if np.where(file['time']==x)[0].size > 0]

In [43]:
ii

[0, 576, 1152, 1728, 2304, 2880]

In [27]:
data_obj.generate_noise("psd", 300)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/home/hruedisser/miniconda3/envs/newtest/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_25285/3518075560.py", line 1, in <module>
    data_obj.generate_noise("psd", 300)
  File "/home/hruedisser/py3DCORE_h4c/py3dcore_h4c/fitter/base.py", line 588, in generate_noise
    data = observer_obj.get([dt_s, dt_e], "mag", reference_frame=self.reference_frame, sampling_freq=sampling_freq, use_cache=True, as_endpoints=True)
  File "/home/hruedisser/py3DCORE_h4c/py3dcore_h4c/fitter/base.py", line 411, in get
    ii = [np.where(self.data['time']==x)[0][0] for x in tt]
  File "/home/hruedisser/py3DCORE_h4c/py3dcore_h4c/fitter/base.py", line 411, in <listcomp>
    ii = [np.where(self.data['time']==x)[0][0] for x in tt]
IndexError: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurre

In [12]:
data_obj.generate_data([0])

In [9]:
from py3dcore_h4c.fitter.base import FittingData

data_obj = FittingData(fitter.observers, 'HEEQ') 

In [74]:
fitter.observers

[['PSP',
  [datetime.datetime(2022, 6, 2, 13, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2022, 6, 2, 14, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2022, 6, 2, 15, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2022, 6, 2, 16, 0, tzinfo=datetime.timezone.utc)],
  datetime.datetime(2022, 6, 2, 12, 0, tzinfo=datetime.timezone.utc),
  datetime.datetime(2022, 6, 3, 6, 0, tzinfo=datetime.timezone.utc),
  None]]

In [50]:
t_psp = [
        datetime.datetime(2022, 9, 11, 0, tzinfo=datetime.timezone.utc),
        datetime.datetime(2022, 6, 2, 14, tzinfo=datetime.timezone.utc) ,
        datetime.datetime(2022, 6, 2, 15, tzinfo=datetime.timezone.utc),
        datetime.datetime(2022, 6, 2, 16, tzinfo=datetime.timezone.utc),
    ] 

In [87]:
data.loc[t_psp]

KeyError: "None of [DatetimeIndex(['2022-06-02 13:00:00+00:00', '2022-06-02 14:00:00+00:00',\n               '2022-06-02 15:00:00+00:00', '2022-06-02 16:00:00+00:00'],\n              dtype='datetime64[ns, UTC]', freq=None)] are in the [index]"

In [52]:
datetime.datetime.timestamp(t_psp[0])

1662854400.0

In [37]:
data[t_psp]

KeyError: "None of [DatetimeIndex(['2022-09-11 00:00:00+00:00', '2022-06-02 14:00:00+00:00',\n               '2022-06-02 15:00:00+00:00', '2022-06-02 16:00:00+00:00'],\n              dtype='datetime64[ns, UTC]', freq=None)] are in the [columns]"

In [38]:
data.index[0]

Timestamp('2022-09-01 00:00:00')